require: rubocop-rails

AllCops:
  Exclude:
    - bin/bundle
    - Gemfile
    - db/**.*
    - examples/**.*
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
